- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/domain/member/Member.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/domain/store/StoreMember.java
- src/main/java/graduate/schedule/domain/store/StoreMemberAvailableTime.java
- src/main/java/graduate/schedule/domain/store/StoreMemberGrade.java
- src/main/java/graduate/schedule/domain/store/StoreMemberWorkingTime.java
- src/main/java/graduate/schedule/repository/StoreRepository.java
- src/main/java/graduate/schedule/service/MemberService.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: entity setting

- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/domain/store/StoreMember.java
- src/main/java/graduate/schedule/dto/web/response/CreateStoreRequestDTO.java
- src/main/java/graduate/schedule/dto/web/response/CreateStoreResponseDTO.java
- src/main/java/graduate/schedule/repository/StoreRepository.java
- src/main/java/graduate/schedule/service/StoreService.java
로그인 구현 이후 request body에서 memberId 제거,
헤더에 access token으로 받는 것으로 수정 예정
> feat: create store(가게 생성) api 구현

- src/main/java/graduate/schedule/common/exception/StoreException.java
- src/main/java/graduate/schedule/common/exception_handler/StoreExceptionControllerAdvice.java
- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/domain/store/StoreMember.java
- src/main/java/graduate/schedule/dto/web/request/JoinStoreRequestDTO.java
- src/main/java/graduate/schedule/dto/web/request/SearchStoreWithInviteCodeRequestDTO.java
- src/main/java/graduate/schedule/dto/web/response/SearchStoreWithInviteCodeResponseDTO.java
- src/main/java/graduate/schedule/repository/StoreMemberRepository.java
- src/main/java/graduate/schedule/repository/StoreRepository.java
- src/main/java/graduate/schedule/service/StoreService.java
<h2>1. 초대 코드로 가게 조회</h2>
고용인으로 등록
<h2>2. 가게 참가</h2>
피고용인으로 등록
> feat: 초대 코드로 가게 조회 및 가게 참가

- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/domain/store/StoreMember.java
- src/main/java/graduate/schedule/domain/store/StoreMemberGrade.java
- src/main/java/graduate/schedule/domain/store/StoreMemberWorkingTime.java
- src/main/java/graduate/schedule/repository/StoreRepository.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 초대 코드 검사 기능 추가

- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/domain/store/StoreMemberWorkingTime.java
- src/main/java/graduate/schedule/dto/web/request/RegenerateInviteCodeRequestDTO.java
- src/main/java/graduate/schedule/dto/web/response/RegenerateInviteCodeResponseDTO.java
- src/main/java/graduate/schedule/repository/StoreMemberRepository.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 초대 코드 재발급 api 구현

- src/main/java/graduate/schedule/common/exception_handler/BaseExceptionControllerAdvice.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/dto/web/response/CreateStoreRequestDTO.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 가게 생성시 암호화 된 사업자등록번호 추가

- build.gradle
- src/main/java/graduate/schedule/business/BusinessCheckClient.java
- src/main/java/graduate/schedule/business/BusinessDataDTO.java
- src/main/java/graduate/schedule/business/BusinessValidateRequestDTO.java
- src/main/java/graduate/schedule/common/exception/BusinessException.java
- src/main/java/graduate/schedule/common/exception_handler/BusinessExceptionControllerAdvice.java
- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/config/FeignClientConfig.java
- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/dto/business/BusinessValidateResponseDTO.java
- src/main/java/graduate/schedule/dto/business/BusinessValidatedDTO.java
- src/main/java/graduate/schedule/dto/web/request/BusinessProofRequestDTO.java
- src/main/java/graduate/schedule/repository/StoreRepository.java
- src/main/java/graduate/schedule/service/BusinessCheckService.java
- src/main/java/graduate/schedule/service/StoreService.java
- src/main/resources/application.yml
> feat: 서비스 내 가게 존재 여부 및 사업자 진위 여부 확인 api 구현

- src/main/java/graduate/schedule/service/BusinessCheckService.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 사업자 진위 여부 확인 응답 값으로 valid/invalid 검사

- src/main/java/graduate/schedule/common/exception/StoreMemberException.java
- src/main/java/graduate/schedule/common/exception_handler/StoreMemberExceptionControllerAdvice.java
- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/domain/store/RequiredTimeAndHeadCount.java
- src/main/java/graduate/schedule/domain/store/RequiredTimeInDay.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/domain/store/StoreMemberAvailableTime.java
- src/main/java/graduate/schedule/domain/store/StoreMemberWorkingTime.java
- src/main/java/graduate/schedule/dto/store/WorkScheduleOnDayDTO.java
- src/main/java/graduate/schedule/dto/store/WorkerAndTimeDTO.java
- src/main/java/graduate/schedule/dto/store/WorkingHeadCountDTO.java
- src/main/java/graduate/schedule/dto/web/response/WorkScheduleOnMonthResponseDTO.java
- src/main/java/graduate/schedule/repository/MemberRepository.java
- src/main/java/graduate/schedule/repository/RequiredTimeAndHeadCountRepository.java
- src/main/java/graduate/schedule/repository/StoreMemberRepository.java
- src/main/java/graduate/schedule/repository/StoreMemberWorkingTimeRepository.java
- src/main/java/graduate/schedule/repository/StoreRepository.java
- src/main/java/graduate/schedule/service/StoreService.java
- src/main/java/graduate/schedule/utils/DateAndTimeFormatter.java
> feat: 특정 달의 모든 근무 일정 조회 api 구현

- .gitignore
- build.gradle
- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/FCMController.java
- src/main/java/graduate/schedule/domain/member/Member.java
- src/main/java/graduate/schedule/dto/fcm/FCMMessage.java
- src/main/java/graduate/schedule/dto/web/request/FcmSendRequestDTO.java
- src/main/java/graduate/schedule/service/FirebaseCloudMessageService.java
- src/main/java/graduate/schedule/service/StoreService.java
- src/main/resources/application.yml
> feat: FCM으로 푸시 알림 구현하기

- src/main/java/graduate/schedule/common/exception/StoreMemberTimeException.java
- src/main/java/graduate/schedule/common/exception_handler/StoreMemberTimeExceptionControllerAdvice.java
- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/domain/store/StoreMemberAvailableTime.java
- src/main/java/graduate/schedule/dto/web/request/AddAvailableScheduleRequestDTO.java
- src/main/java/graduate/schedule/dto/web/request/DeleteAvailableScheduleRequestDTO.java
- src/main/java/graduate/schedule/dto/web/response/AddAvailableScheduleResponseDTO.java
- src/main/java/graduate/schedule/service/FirebaseCloudMessageService.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 일 단위 가능한 시간 추가 및 삭제 api 구현

- src/main/java/graduate/schedule/controller/FCMController.java
- src/main/java/graduate/schedule/dto/fcm/FCMMessage.java
- src/main/java/graduate/schedule/dto/web/request/FcmSendRequestDTO.java
- src/main/java/graduate/schedule/service/FirebaseCloudMessageService.java
- src/main/resources/application.yml
> feat: FCM 푸시 알림 테스트용 api 확인 및 수정

- src/main/java/graduate/schedule/controller/MemberController.java
- src/main/java/graduate/schedule/controller/StoreController.java
- src/main/java/graduate/schedule/dto/web/request/RequestWithOnlyMemberIdDTO.java
- src/main/java/graduate/schedule/dto/web/request/store/AddAvailableScheduleRequestDTO.java
- src/main/java/graduate/schedule/dto/web/request/store/CreateStoreRequestDTO.java
- src/main/java/graduate/schedule/dto/web/request/store/DeleteAvailableScheduleRequestDTO.java
- src/main/java/graduate/schedule/dto/web/request/store/JoinStoreRequestDTO.java
- src/main/java/graduate/schedule/dto/web/request/store/RequestWithOnlyStoreIdDTO.java
- src/main/java/graduate/schedule/service/MemberService.java
- src/main/java/graduate/schedule/service/StoreService.java
access token 받아 interceptor에서 Member로 반환
> refactor: request body에서 memberId 삭제

- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/ExecutiveController.java
- src/main/java/graduate/schedule/domain/store/StoreMember.java
- src/main/java/graduate/schedule/domain/store/StoreMemberGrade.java
- src/main/java/graduate/schedule/dto/web/request/SetMemberGradeRequestDTO.java
- src/main/java/graduate/schedule/service/ExecutiveService.java
- src/main/java/graduate/schedule/service/StoreService.java
고용 형태는 무조건 `매니저`, `직원`, `아르바이트`로 받아야 함
ex. 알바 X
> feat: 직원 고용 형태 수정 api 구현

- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/ExecutiveController.java
- src/main/java/graduate/schedule/domain/store/StoreMemberGrade.java
- src/main/java/graduate/schedule/dto/web/request/DeleteStoreMemberRequestDTO.java
- src/main/java/graduate/schedule/service/ExecutiveService.java
> feat: 피고용인 삭제 api 구현

- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/ExecutiveController.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/repository/MemberRepository.java
- src/main/java/graduate/schedule/repository/StoreMemberAvailableTimeRepository.java
- src/main/java/graduate/schedule/repository/StoreMemberRepository.java
- src/main/java/graduate/schedule/repository/StoreMemberWorkingTimeRepository.java
- src/main/java/graduate/schedule/service/ExecutiveService.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 가게 삭제 api 구현

- src/main/java/graduate/schedule/common/exception/StoreScheduleException.java
- src/main/java/graduate/schedule/common/exception_handler/StoreScheduleExceptionControllerAdvice.java
- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/ExecutiveController.java
- src/main/java/graduate/schedule/domain/store/Store.java
- src/main/java/graduate/schedule/domain/store/StoreSchedule.java
- src/main/java/graduate/schedule/dto/store/WorkerAndTimeDTO.java
- src/main/java/graduate/schedule/dto/web/request/ChangeWorkerRequestDTO.java
- src/main/java/graduate/schedule/dto/web/request/ChangeWorkingTimeRequestDTO.java
- src/main/java/graduate/schedule/repository/StoreScheduleRepository.java
- src/main/java/graduate/schedule/service/ExecutiveService.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 고용인 제한 기능 (근무자 수정 / 근무 시간 수정 / 근무 정보 삭제) api 구현

- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/ExecutiveController.java
- src/main/java/graduate/schedule/domain/store/StoreMember.java
- src/main/java/graduate/schedule/domain/store/StoreSchedule.java
- src/main/java/graduate/schedule/dto/web/response/ChangeScheduleResponseDTO.java
- src/main/java/graduate/schedule/service/ExecutiveService.java
- src/main/java/graduate/schedule/service/MemberService.java
- src/main/java/graduate/schedule/service/StoreService.java
> feat: 근무 정보 수정 api response 수정(추가)

- .gitignore
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
> feat: log to file

- src/main/java/graduate/schedule/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/graduate/schedule/controller/ExecutiveController.java
- src/main/java/graduate/schedule/controller/ScheduleController.java
- src/main/java/graduate/schedule/dto/web/response/executive/ChangeScheduleResponseDTO.java
- src/main/java/graduate/schedule/service/AuthService.java
- src/main/java/graduate/schedule/service/ExecutiveService.java
- src/main/java/graduate/schedule/service/MemberService.java
- src/main/java/graduate/schedule/service/ScheduleService.java
> feat: 대타 수락 api 구현

- .github/workflows/deploy.yml
> chore: deploy.yml 수정

- src/main/java/graduate/schedule/ScheduleApplication.java
- src/main/java/graduate/schedule/domain/store/StoreAvailableTimeByDay.java
- src/main/java/graduate/schedule/dto/store/EmployeeDTO.java
- src/main/java/graduate/schedule/repository/StoreMemberRepository.java
- src/main/java/graduate/schedule/repository/StoreScheduleRepository.java
- src/main/java/graduate/schedule/service/ExecutiveService.java
- src/main/java/graduate/schedule/service/NotificationService.java
- 매월 8일 00시 가능한 고정 시간 데이터 저장 - 00시
- 매월 8일 다음달 가능 시간 입력 시작 알림 - 12시
- 대체 근무 요청이 있는데, 수락이 없는 경우 - 매일 12시
> feat: 매일, 매월 특정 날짜에 사용자들에게 전송해야 하는 푸시 알림 구현
